% example_strip_slit_plot_contores_1.m
% Nasser, June 16, 2019
clc;clear; 
% To plot Figure 29 in Section 9 of the paper:
% COMPUTATION OF CONFORMAL INVARIANTS 
%
% The data files 
% x1_pt.mat, y1_pt.mat, u1_pt.mat
% were generated by the file
% example_strip_slit_save_contores_1.m
%
%
%
z1    =  0;
x=load('x1_pt.mat','-ascii');
y=load('y1_pt.mat','-ascii');
u=load('u1_pt.mat','-ascii');
%
figure;
cntv  =  [1.7:0.5:6,6.5,7.5,9];
contour(x,y,u,cntv,'ShowText','on','Color','k')
hold on
plot(0,0,'or','MarkerFaceColor','r')
plot([-3 3],[-pi/2  -pi/2],'k','LineWidth',2)
plot([-3 3],[+pi/2  +pi/2],'k','LineWidth',2)

axis equal
axis([-3.0 3.0 -1.65 1.65])
axis off
set(gca,'LooseInset',get(gca,'TightInset'))
% print -depsc fig_strip_cont
% print -dpdf  fig_strip_cont
%