% example_two_slits_plot_contores_0154.m
% Nasser, June 11, 2019
clc;clear; 
% To plot Figure 20 in Section 7 of the paper:
% COMPUTATION OF CONFORMAL INVARIANTS 
%
% The data files 
% x01_pt.mat, y01_pt.mat, u0154_pt.mat
% were generated by the file
% example_two_slits_save_contores_0154.m
%
%
%
z1=5+4i;
x=load('x01_pt.mat','-ascii');
y=load('y01_pt.mat','-ascii');
u=load('u0154_pt.mat','-ascii');
%
figure
cntv  =  0.9:0.15:2.1;
contour(x,y,u,cntv,'ShowText','on','Color','k')
hold on
plot(real(z1),imag(z1),'or','MarkerFaceColor','r')
plot([0 1],[0 0],'k','LineWidth',2)
axis([-0.0 12 -0.0 10])
axis off
set(gca,'LooseInset',get(gca,'TightInset'))
% print -dpdf  fig_two_seg01_m5_n4
% print -depsc fig_two_seg01_m5_n4