% example_two_slits_error_plot.m
% Nasser, June 11, 2019
clc;clear; 
% To use the error values generated by the file
% example_two_slits_error.m
% to plot Figure 15 in Section 7 of the paper:
% COMPUTATION OF CONFORMAL INVARIANTS 
%
%  
Case_c_2 =  [
          2.1    2.869e-14
          2.6   1.3972e-14
          3.1   1.7234e-14
          3.6   2.3071e-14
          4.1    9.562e-15
          4.6   1.5167e-15
          5.1   8.4551e-15
          5.6   1.4365e-14
          6.1   2.6618e-14
          6.6   1.4948e-14
          7.1   1.0416e-14
          7.6   2.9758e-14
          8.1   3.0795e-14
          8.6    1.828e-14
          9.1   2.9961e-14
          9.6   1.9088e-14
         10.1   2.8606e-14
         ];
%
Case_c_d_1 = [
          2.1   3.1491e-15
          2.6   3.0468e-14
          3.1   2.2774e-14
          3.6   9.4384e-15
          4.1   1.2498e-14
          4.6   4.2099e-14
          5.1    1.927e-14
          5.6    1.025e-15
          6.1   2.4006e-14
          6.6   1.0082e-14
          7.1   2.6587e-14
          7.6   3.3141e-14
          8.1    2.031e-14
          8.6   3.1092e-14
          9.1   3.7448e-14
          9.6    1.399e-14
         10.1   3.0842e-14   
         ];
%
%
figure
plot(Case_c_2(:,1),log10(Case_c_2(:,2)),'-k','LineWidth',1)
hold on
plot(Case_c_d_1(:,1),log10(Case_c_d_1(:,2)),'-b','LineWidth',1)

legend({'$c=2$','$c=d-1$'},...
        'FontSize',18,'Interpreter','latex','Location','northeast');

xlabel('{$d$}','FontSize',18,'Interpreter','latex');
ylabel('$\log_{10}$(Relative error)','FontSize',18,'Interpreter','latex');
set(gca,'XTick',[2:1:10],'FontSize',18);
set(gca,'YTick',[-15:1:-12]);
axis([2 10 -15 -12])
grid(gca,'minor')
grid on
set(gca, 'XMinorTick','on')
set(gca, 'YMinorTick','on')
ax=gca;
ax.GridAlpha=0.75;
ax.MinorGridAlpha=0.75;
set(gca,'LooseInset',get(gca,'TightInset'))
% print -dpdf  fig_two_seg_err
% print -depsc fig_two_seg_err
%