% example_half_slit_plot_contores_2.m
% Nasser, June 16, 2019
clc;clear; 
% To plot Figure 25 in Section 8 of the paper:
% COMPUTATION OF CONFORMAL INVARIANTS 
%
% The data files 
% x2_pt.mat, y2_pt.mat, u2_pt.mat
% were generated by the file
% example_half_slit_save_contores_2.m
%
%
%
z1    =  2i;
x=load('x2_pt.mat','-ascii');
y=load('y2_pt.mat','-ascii');
u=load('u2_pt.mat','-ascii');
%
figure;
cntv  =  [1.5:0.5:6,7,8];
contour(x,y,u,cntv,'ShowText','on','Color','k')
hold on
plot(0,2,'or','MarkerFaceColor','r')
plot([-3 3],[0 0],'k','LineWidth',2)

axis([-3.0 3.0 -0.1 3])
axis off
set(gca,'LooseInset',get(gca,'TightInset'))
% print -depsc fig_half_cont2
% print -dpdf  fig_half_cont2
