% example_half_slit_cap_error_plot.m
% Nasser, June 16, 2019
clc;clear; 
% To use the error values generated by the file
% example_half_slit_vertical_error_compute.m
% to plot Figure 22 
% 
% and to use the values of the capacity generated by the files
% example_half_slit_horizontal_cap_compute.m
% example_half_slit_vertical_cap_compute.m
% to plot Figure 23 
% 
% in Section 8 of the paper:
% COMPUTATION OF CONFORMAL INVARIANTS 
%
%
% from example_half_slit_vertical_error_compute.m
error_ver_mov_ver_slit = [
                      0.05      1.28169983775455e-13
                       0.2      1.03392168695715e-14
                       0.4      4.52980691386808e-14
                       0.6      5.68892021256787e-15
                       0.8      2.29449653195329e-14
                         1      2.10022702169776e-14
                       1.2      6.21832623428096e-15
                       1.4      8.59854827750828e-15
                       1.6      1.98386660385561e-16
                       1.8      1.04545136476329e-14
                         2       1.4138124679915e-14
                       2.2      1.55923411434107e-14
                       2.4      1.97307481834954e-14
                       2.6      1.08707803717851e-14
                       2.8      1.30485956150623e-14
                         3      1.84595282140804e-14
                       3.2      2.74987291546803e-14
                       3.4      2.27086159693841e-14
                       3.6      3.03115768690713e-14
                       3.8      1.06176068060332e-14
                         4      1.68285074575281e-14
                       4.2      2.12606237593924e-14
                       4.4      7.38473792877785e-15
                       4.6      1.45385253396187e-14
                       4.8      1.97191696430073e-14
                         5      3.31472073961486e-14
                       5.2      3.06280703998576e-14
                       5.4      2.16476437327762e-14
                       5.6       2.9800807638032e-14
                       5.8      1.30166238756125e-14
                         6      2.00998886312895e-14
];
%
% from example_half_slit_horizontal_cap_compute.m
hor_extend = [
                      0.05          1.14642573467585
                     0.075          1.23800461534809
                       0.1          1.31237888922948
                      0.15          1.43375157961917
                       0.2          1.53439310061267
                       0.3          1.70270230417883
                       0.4          1.84614553111767
                       0.5          1.97491514761356
                       0.6          2.09392673802548
                       0.7          2.20596199234156
                       0.8            2.312759279404
                       0.9           2.4154812604512
                         1          2.51494489756504
                       1.1          2.61174617312612
                       1.2          2.70633285438555
                       1.3          2.79904944294121
                       1.4          2.89016624499191
                       1.5          2.97989889198823
                       1.6          3.06842186520629
                       1.7          3.15587811621268
                       1.8          3.24238606531109
                       1.9          3.32804479136497
                         2          3.41293794479942
                       2.1          3.49713674078187
                       2.2           3.5807018242585
                       2.3          3.66368580742393
                       2.4          3.74613513153308
                       2.5          3.82809001188329
                       2.6          3.90958587053024
                       2.7          3.99065408422403
                       2.8          4.07132259473715
                       2.9          4.15161641004753
                         3          4.23155801833645
                         ];
%
% from example_half_slit_vertical_cap_compute.m
ver_extend = [
                      0.05          1.14644752527233
                     0.075          1.23806179496948
                       0.1          1.31249313646455
                      0.15          1.43405849148611
                       0.2          1.53501833448635
                       0.3          1.70443732092082
                       0.4          1.84977990133407
                       0.5           1.9814337549406
                       0.6          2.10452077157188
                       0.7          2.22204461220613
                       0.8          2.33598571003155
                       0.9          2.44777371061154
                         1          2.55852314234207
                       1.1          2.66916505518748
                       1.2          2.78052846205533
                       1.3          2.89339637976124
                       1.4          3.00854931674334
                       1.5           3.1268038453922
                       1.6          3.24905174417214
                       1.7          3.37630473143443
                       1.8          3.50975064539291
                       1.9          3.65082924797478
                         2          3.80134048001095
                       2.1          3.96360693068296
                       2.2          4.14072992108875
                       2.3          4.33701538339002
                       2.4          4.55872841593536
                       2.5          4.81554035089266
                       2.6          5.12360954778149
                       2.7          5.51317820782613
                      2.75          5.75671784660717
                       2.8          6.05208033806439
                      2.85          6.42946703101358
                     2.875          6.66710085745364
                       2.9          6.95667526718554
                     2.925          7.32838758929427
                      2.95          7.85003134304205
                      ];
%
%
figure
plot(hor_extend(:,1),hor_extend(:,2),'-b','LineWidth',1)
hold on
plot(ver_extend(:,1),ver_extend(:,2),'--k','LineWidth',1)
legend('Hor. Segment','Ver. Segment','Location','northwest');
xlabel('{$s$}','FontSize',18,'Interpreter','latex');
ylabel('{Capacity}','FontSize',18,'Interpreter','latex');

set(gca,'XTick',[0:1:3],'FontSize',18);
set(gca,'YTick',[0:2:10]);
axis([0 3 0 10])
grid(gca,'minor')
grid on
set(gca, 'XMinorTick','on')
set(gca, 'YMinorTick','on')
ax=gca;
ax.GridAlpha=0.75;
ax.MinorGridAlpha=0.75;
set(gca,'LooseInset',get(gca,'TightInset'))
% print -depsc cap_half_extend
% print -dpdf  cap_half_extend
%
%
figure
plot(error_ver_mov_ver_slit(:,1),log10(error_ver_mov_ver_slit(:,2)),'-b','LineWidth',1)
xlabel('{$s$}','FontSize',18,'Interpreter','latex');
ylabel('$\log_{10}$(Relative error)','FontSize',18,'Interpreter','latex');

set(gca,'XTick',[0:1:6],'FontSize',18);
set(gca,'YTick',[-16:-12]);
axis([0 6 -16 -12])
grid(gca,'minor')
grid on
set(gca, 'XMinorTick','on')
set(gca, 'YMinorTick','on')
ax=gca;
ax.GridAlpha=0.75;
ax.MinorGridAlpha=0.75;
set(gca,'LooseInset',get(gca,'TightInset'))
% print -depsc half_error_ver_slit
% print -dpdf  half_error_ver_slit
%
%